
@"C:\Users\bradr\Database Labs\Lab1\DefaultScripts\cleanup_oracle.sql";
@"C:\Users\bradr\Database Labs\Lab1\DefaultScripts\create_truck_tables.sql";
@"C:\Users\bradr\Database Labs\Lab1\DefaultScripts\truck_inserts.sql";


-- Open log file.
SPOOL lab1.log;



-- Perform Steps 6 - 16 of lab1 in this region

--#6
CREATE TABLE MAINTENANCE (
  MAINTENANCE_ID       NUMBER
, MAINTENANCE_DATE     DATE          CONSTRAINT  NN_MAINTENANCE_1 NOT NULL
, MAINTENANCE_TYPE     VARCHAR2(45)  CONSTRAINT  NN_MAINTENANCE_2 NOT NULL 
, NOTES                VARCHAR2(45) 
, VEHICLE_ID           NUMBER        CONSTRAINT  NN_MAINTENANCE_3 NOT NULL
, EMPLOYEE_ID          NUMBER        CONSTRAINT  NN_MAINTENANCE_4 NOT NULL
, CONSTRAINT PK_MAINTENANCE PRIMARY KEY(MAINTENANCE_ID)
, CONSTRAINT FK__MAINT_EMPLOYEE FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
, CONSTRAINT FK_MAINT_VEHICLE FOREIGN KEY(VEHICLE_ID) REFERENCES VEHICLE(VEHICLE_ID)
, CONSTRAINT CK_N CHECK (MAINTENANCE_TYPE='LOF' OR MAINTENANCE_TYPE='Brake Inspection')
);

  -- create sequence -- 
CREATE SEQUENCE maintenance_s1 START WITH 1; 

-- create unique index -- 
CREATE UNIQUE INDEX MAINTENANCE_IDX1 ON  MAINTENANCE(MAINTENANCE_ID, MAINTENANCE_DATE, MAINTENANCE_TYPE);


--#7
INSERT INTO MAINTENANCE
VALUES (
  maintenance_s1.NEXTVAL
, '19-NOV-2016'
, 'LOF'
, NULL
, (SELECT VEHICLE_ID FROM VEHICLE WHERE NAME = 'Mad Max')
, (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE FIRST_NAME = 'Mike'));


-- maintenance_id
--maintenance_date
--type
--notes
--vehicle id 
-- employee_id

INSERT INTO MAINTENANCE 
VALUES(
  MAINTENANCE_S1.NEXTVAL
, '24-NOV-2016'
, 'Brake Inspection'
, NULL
, (SELECT VEHICLE_ID FROM VEHICLE WHERE NAME = 'Classy Cat')
, (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE FIRST_NAME = 'Mike'));

--#8
CREATE TABLE INCIDENT(
  INCIDENT_ID         NUMBER
, INCIDENT_DATE       DATE          CONSTRAINT NN_INCIDENT_1 NOT NULL 
, INCIDENT_TYPE       VARCHAR2(45)  CONSTRAINT NN_INCIDENT_2 NOT NULL 
, EMPLOYEE_ID         NUMBER        CONSTRAINT NN_INCIDENT_3 NOT NULL 
, VEHICLE_ID          NUMBER        CONSTRAINT NN_INCIDETN_4 NOT NULL 
, NOTES               VARCHAR2(45)  CONSTRAINT NN_INCIDENT_5 NOT NULL
, CONSTRAINT PK_INCIDENT PRIMARY KEY(INCIDENT_ID) 
, CONSTRAINT FK_INCIDENT_EMPLOYEE FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
, CONSTRAINT FK_INCIDENT_VEHICLE FOREIGN KEY(VEHICLE_ID) REFERENCES VEHICLE(VEHICLE_ID)
, CONSTRAINT INCIDENT_TYP_CK CHECK (INCIDENT_TYPE = 'Overweight' OR INCIDENT_TYPE = 'Speeding' OR INCIDENT_TYPE = 'Accident')
); 

  -- create sequence -- 
CREATE SEQUENCE INCIDENT_S1 START WITH 1; 

-- create unique index -- 
CREATE UNIQUE INDEX INCIDENT_IDX1 ON  INCIDENT(INCIDENT_ID, INCIDENT_DATE, INCIDENT_TYPE);

--#9 
INSERT INTO INCIDENT
VALUES (
  INCIDENT_S1.NEXTVAL
, '28-DEC-2016'
, 'Overweight'
, (SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE FIRST_NAME = 'Matt')
, (SELECT VEHICLE_ID FROM VEHICLE WHERE NAME = 'Classy Cat'));


--#10 
CREATE TABLE DRUGTEST ( 
  DRUGTEST_ID           NUMBER
, DRUGTEST_DATE         DATE          CONSTRAINT NN_DRUGTEST_1 NOT NULL 
, EMPLOYEE_ID           NUMBER        NOT NULL 
, RESULTS               VARCHAR2(45)  CONSTRAINT NN_DRUGTEST_2 NOT NULL 
, CONSTRAINT PK_DRUGTEST PRIMARY KEY(DRUGTEST_ID)
, CONSTRAINT FK_DRUGT_EMPLOYEE FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
, CONSTRAINT CK_DRUGT CHECK (RESULTS = 'Pending' OR RESULTS = 'Pass' OR RESULTS = 'Fail')
);

  -- create sequence -- 
CREATE SEQUENCE DRUGTEST_S1 START WITH 1; 

-- create unique index -- 
CREATE UNIQUE INDEX DRUDGTEST_IDX1 ON DRUGTEST(DRUGTEST_ID, DRUGTEST_DATE, RESULTS);


--#11
INSERT INTO CITY
VALUES (
  CITY_S1.NEXTVAL
, 'San Francisco'
, 'SFO'
);

--#12
INSERT INTO MILEAGE
VALUES (
  MILEAGE_S1.NEXTVAL
, (SELECT CITY_ID FROM CITY WHERE CODE = 'BOI')
, CITY_S1.CURRVAL
, 800); 

INSERT INTO MILEAGE
VALUES ( 
  MILEAGE_S1.NEXTVAL
, (SELECT CITY_ID FROM CITY WHERE CODE = 'SLC')
, CITY_S1.CURRVAL
, 737);

INSERT INTO MILEAGE 
VALUES(
  MILEAGE_S1.NEXTVAL
, (SELECT CITY_ID FROM CITY WHERE CODE = 'SEA')
, CITY_S1.CURRVAL
, 809); 


--#13
ALTER TABLE MAINTENANCE
ADD CONSTRAINT tire_insp_ck CHECK (MAINTENANCE_TYPE='Tire Inspection')
ENABLE NOVALIDATE;

--#14
ALTER TABLE INCIDENT
DROP CONSTRAINT INCIDENT_TYP_CK;
ALTER TABLE INCIDENT 
ADD CONSTRAINT INCIDENT_TYP_CK  CHECK(INCIDENT_TYPE = 'Overweight' OR INCIDENT_TYPE = 'Speeding' OR INCIDENT_TYPE = 'Accident' OR INCIDENT_TYPE ='Sleep Log')
ENABLE NOVALIDATE;


--#15
ALTER TABLE CLIENT
MODIFY PHONE
CONSTRAINT NN_CLIENT_7 NOT NULL;

--#16 
ALTER TABLE EMPLOYEE
RENAME COLUMN FIRE_DATE 
TO TERMINATION_DATE;

-- Close log file.
SPOOL OFF;
